version: '2'
services:

    # btc is an image of bitcoin node which used as base image for btcd and
    # btccli. The environment variables default values determined on stage of
    # container start within starting script.
    btc:
      image: btcd
      build:
        context: btcd/
      volumes:
            - shared:/rpc
            - bitcoin:/data
      environment:
        - RPCUSER
        - RPCPASS
        - NETWORK

    btcd:
        extends: btc
        container_name: btcd
        environment:
          - DEBUG
          - MINING_ADDRESS
        entrypoint: ["./start-btcd.sh"]

    btcctl:
        extends: btc
        container_name: btcctl
        links:
            - "btcd:rpcserver"
        entrypoint: ["./start-btcctl.sh"]

    lnd:
        image: lnd
        build:
          context: lnd/
        environment:
          - RPCUSER
          - RPCPASS
          - NETWORK
          - CHAIN
          - DEBUG
        volumes:
            - shared:/rpc
        entrypoint: ["./start-lnd.sh"]

    truffle:
        image: truffle
        build:
          context: ../
          dockerfile: docker/truffle/Dockerfile
        ports:
          - "8545:8545"
        environment:
            - DOCKER=true
        entrypoint: ["./start-truffle.sh"]

    pg:
        image: postgres
        # restart: always
        environment:
          POSTGRES_PASSWORD:
          POSTGRES_DB: drawbridge
        ports:
          - "5432:5432"
        build:
          context: ../
          dockerfile: docker/postgres/Dockerfile

    pg_admin:
        image: adminer
        # restart: always
        ports:
          - "8080:8080"

    alice_lnd:
      extends: lnd
      container_name: alice_lnd
      links:
          - "btcd:blockchain"
      ports:
        - "10009:10009"

    bob_lnd:
      extends: lnd
      container_name: bob_lnd
      links:
          - "btcd:blockchain"
      ports:
        - "10101:10009"

    drawbridge:
      build:
        context: ../
        dockerfile: docker/drawbridge/Dockerfile
      volumes:
        - shared:/rpc

    alice_db:
      extends: drawbridge
      container_name: alice_db
      links:
          - "truffle:ethereum"
          - "alice_lnd:lnd"
      ports:
        - "8080:8080"
        - "9735:9735"
      entrypoint: ["make start"]

    bob_db:
      extends: drawbridge
      container_name: bob_db
      links:
          - "truffle:ethereum"
          - "bob_lnd:lnd"
      ports:
        - "8081:8080"
        - "9736:9735"
      entrypoint: ["./start-drawbridge.sh"]

volumes:
  # shared volume is need to store the btcd rpc certificates and use it within
  # btcctl and lnd containers.
  shared:
    driver: local

  # bitcoin volume is needed for maintaining blockchain persistence
  # during btcd container recreation.
  bitcoin:
    driver: local

  # litecoin volume is needed for maintaining blockchain persistence
  # during ltcd container recreation.
  litecoin:
    driver: local
